version: "3.9"

services:

  healthcare-ai:

    build: .

    container_name: healthcare-ai

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store

    env_file:
      - .env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped